[workspace]
members = [
    "valinoreth",
    "valinoreth_proofs",
]
resolver = "2"

[workspace.dependencies]
creusot-std = { version = "0.10", features = ["nightly"] }

[patch.crates-io]
creusot-std = { path = "../elicitation/vendor/creusot-std" }
pearlite-syn = { path = "../elicitation/vendor/pearlite-syn" }
